"""Initial migration

Revision ID: ce799870c99a
Revises: 
Create Date: 2023-11-05 15:53:49.509396

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce799870c99a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celebrities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("occupation", sa.String(), nullable=False),
        sa.Column("short_bio", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celebrities_id"), "celebrities", ["id"], unique=False)
    op.create_table(
        "daily_schedule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("celebrity_id", sa.UUID(), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_schedule_id"), "daily_schedule", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_schedule_id"), table_name="daily_schedule")
    op.drop_table("daily_schedule")
    op.drop_index(op.f("ix_celebrities_id"), table_name="celebrities")
    op.drop_table("celebrities")
    # ### end Alembic commands ###
