version: "3.8"
services:
  postgres_db:
    image: postgres:16
    container_name: postgres_celebrity_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  celebrity_service:
    image: celebrity_app
    build:
      dockerfile: dockerfile
    container_name: celebrity_app
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - .:/celebrity_daily_routine
    depends_on:
      - postgres_db

volumes:
  postgresdata: